const assert=require('node:assert/strict');
const submit=require('../netlify/functions/submit-order.cjs').handler;
const createQuote=require('../netlify/functions/create-order-quote.cjs').handler;
const uploadQuote=require('../netlify/functions/quote-upload-url.cjs').handler;
const validateQuote=require('../netlify/functions/quote-validate-receipt.cjs').handler;
const placeQuote=require('../netlify/functions/place-quoted-order.cjs').handler;
const track=require('../netlify/functions/order-status.cjs').handler;
const orderReceipt=require('../netlify/functions/order-receipt.cjs').handler;
const uploadPayment=require('../netlify/functions/payment-upload-url.cjs').handler;
const submitPayment=require('../netlify/functions/payment-submit.cjs').handler;
const paymentReceipt=require('../netlify/functions/payment-receipt-url.cjs').handler;
const invite=require('../netlify/functions/invite-staff.cjs').handler;
const shared=require('../netlify/lib/shared.cjs');
const {randomUUID}=require('node:crypto');
const token=randomUUID(),quoteId=randomUUID();
const event={httpMethod:'POST',headers:{host:'example.netlify.app',origin:'https://example.netlify.app','x-nf-client-connection-ip':'192.0.2.1'},body:JSON.stringify({token})};
const uuid=()=>randomUUID();
(async()=>{
 assert.equal((await submit({...event,httpMethod:'GET'})).statusCode,405);
 const retiredSubmission=await submit(event);assert.equal(retiredSubmission.statusCode,410);assert.match(retiredSubmission.body,/bank-transfer or Paystack checkout/i);assert.doesNotMatch(retiredSubmission.body,/WhatsApp/i);
 assert.equal((await createQuote({...event,headers:{...event.headers,origin:'https://elsewhere.test'}})).statusCode,403);
 assert.equal((await createQuote({...event,body:'{'})).statusCode,400);
 process.env.SUPABASE_URL='https://project.example.test';
 process.env.SUPABASE_SECRET_KEY='sb_secret_TEST_NOT_A_REAL_KEY';
 const customer={name:'Test Customer',phone:'08161248972',fulfillment:'Pickup',address:'',notes:''};
 const options=[{group_id:uuid(),choice_ids:[uuid(),uuid()]}];
 const quoteEvent={...event,body:JSON.stringify({quote_id:quoteId,customer,items:[{id:'wafflin:0',quantity:1,options}]})};
 let quoteRpc;
 global.fetch=async(url,options)=>{assert.ok(String(url).endsWith('/rpc/create_order_quote'));quoteRpc=JSON.parse(options.body);return {ok:true,json:async()=>({quote_id:quoteId,total:7500})};};
 const created=await createQuote(quoteEvent);assert.equal(created.statusCode,200);assert.equal(quoteRpc.p_quote_id,quoteId);assert.equal(quoteRpc.p_fingerprint.length,64);assert.deepEqual(quoteRpc.p_items[0].options,options);assert.ok(!created.body.includes(process.env.SUPABASE_SECRET_KEY));
 global.fetch=async()=>({ok:false,status:400,json:async()=>({message:'Bank-transfer details and payment instructions are not configured. Contact the café before requesting payment.'})});
 const missingPaymentSetup=await createQuote(quoteEvent);assert.equal(missingPaymentSetup.statusCode,409);assert.match(missingPaymentSetup.body,/payment instructions are not configured/i);
 const signedPath=quoteId+'/'+uuid()+'.pdf';let uploadRpc;
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/issue_quote_upload')){uploadRpc=JSON.parse(options.body);return {ok:true,json:async()=>({issued_at:new Date().toISOString(),replaced_paths:[]})};}if(url.includes('/object/upload/sign/payment-receipts/'))return {ok:true,json:async()=>({token:'signed-upload-token'})};throw Error('Unexpected quote upload URL '+url);};
 const signed=await uploadQuote({...event,body:JSON.stringify({quote_id:quoteId,content_type:'application/pdf'})});assert.equal(signed.statusCode,200);const signedBody=JSON.parse(signed.body);assert.equal(signedBody.path.split('/')[0],quoteId);assert.equal(signedBody.token,'signed-upload-token');assert.equal(uploadRpc.p_path,signedBody.path);
 assert.equal((await uploadQuote({...event,body:JSON.stringify({quote_id:quoteId,content_type:'application/x-msdownload'})})).statusCode,400);
 const pdfBytes=Buffer.from('%PDF-1.7 valid receipt');
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/validate_quote_receipt_upload'))return {ok:true,json:async()=>({file_type:'application/pdf',quote_expired:false})};if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>pdfBytes.buffer.slice(pdfBytes.byteOffset,pdfBytes.byteOffset+pdfBytes.byteLength)};throw Error('Unexpected quote receipt validation URL '+url);};
 const checked=await validateQuote({...event,body:JSON.stringify({quote_id:quoteId,path:signedBody.path})});assert.equal(checked.statusCode,200);assert.equal(JSON.parse(checked.body).validated,true);
 let replacedOldPath;
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/issue_quote_upload'))return {ok:true,json:async()=>({replaced_paths:[signedBody.path]})};if(options.method==='DELETE'){replacedOldPath=url;return {ok:true};}if(url.includes('/object/upload/sign/payment-receipts/'))return {ok:true,json:async()=>({token:'webp-upload-token'})};throw Error('Unexpected replacement receipt URL '+url);};
 const webpUpload=await uploadQuote({...event,body:JSON.stringify({quote_id:quoteId,content_type:'image/webp'})});assert.equal(webpUpload.statusCode,200);const webpBody=JSON.parse(webpUpload.body);assert.match(webpBody.path,/\.webp$/);assert.match(replacedOldPath,new RegExp(signedBody.path.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
 const webpBytes=Buffer.from('RIFF\x04\x00\x00\x00WEBP');
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/validate_quote_receipt_upload'))return {ok:true,json:async()=>({file_type:'image/webp',quote_expired:false})};if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>webpBytes.buffer.slice(webpBytes.byteOffset,webpBytes.byteOffset+webpBytes.byteLength)};throw Error('Unexpected WebP validation URL '+url);};
 const checkedWebp=await validateQuote({...event,body:JSON.stringify({quote_id:quoteId,path:webpBody.path})});assert.equal(checkedWebp.statusCode,200);
 let placeRpc;
 global.fetch=async(url,options)=>{url=String(url);if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>webpBytes.buffer.slice(webpBytes.byteOffset,webpBytes.byteOffset+webpBytes.byteLength)};if(url.endsWith('/rpc/place_quoted_order')){placeRpc=JSON.parse(options.body);return {ok:true,json:async()=>({reference:'SS-PLACED',tracking_token:quoteId,total:7500})};}throw Error('Unexpected place quote URL '+url);};
 const placed=await placeQuote({...event,body:JSON.stringify({quote_id:quoteId,path:webpBody.path,payment_reference:'BANK-123'})});assert.equal(placed.statusCode,200);assert.equal(JSON.parse(placed.body).order.reference,'SS-PLACED');assert.equal(placeRpc.p_receipt_path,webpBody.path);assert.ok(!placed.body.includes(process.env.SUPABASE_SECRET_KEY));
 global.fetch=async(url,options)=>{url=String(url);if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>webpBytes.buffer.slice(webpBytes.byteOffset,webpBytes.byteOffset+webpBytes.byteLength)};if(url.endsWith('/rpc/place_quoted_order'))return {ok:true,json:async()=>({error_code:'quote_expired',message:'Expired quote evidence retained'})};throw Error('Unexpected expired quote URL '+url);};
 const expired=await placeQuote({...event,body:JSON.stringify({quote_id:quoteId,path:webpBody.path,payment_reference:''})});assert.equal(expired.statusCode,409);assert.equal(JSON.parse(expired.body).receipt_retained,true);
 global.fetch=async(url,options)=>{url=String(url);if(url.includes('/object/authenticated/payment-receipts/')){const bytes=Buffer.from('not a webp');return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};}if(options.method==='DELETE')return {ok:true};throw Error('Unexpected invalid receipt URL '+url);};
 const invalidFile=await placeQuote({...event,body:JSON.stringify({quote_id:quoteId,path:webpBody.path,payment_reference:''})});assert.equal(invalidFile.statusCode,400);
 assert.notEqual(shared.fingerprint(event),shared.fingerprint({...event,headers:{...event.headers,'x-nf-client-connection-ip':'192.0.2.2'}}));
 assert.equal((await invite(event)).statusCode,401);
 global.fetch=async()=>({ok:true,json:async()=>false});assert.equal((await invite({...event,headers:{...event.headers,authorization:'******'}})).statusCode,403);

 const trackingEvent={...event,body:JSON.stringify({token})};
 assert.equal((await track({...trackingEvent,httpMethod:'GET'})).statusCode,405);
 assert.equal((await track({...trackingEvent,headers:{...event.headers,origin:'https://other.test'}})).statusCode,403);
 assert.equal((await track({...trackingEvent,body:JSON.stringify({token:'SS-GUESSED-REFERENCE'})})).statusCode,400);
 global.fetch=async()=>({ok:true,json:async()=>null});assert.equal((await track(trackingEvent)).statusCode,404);
 global.fetch=async()=>({ok:true,json:async()=>({reference:'SS-TRACKED',status:'preparing',items:[],subtotal:100,total:100,delivery_fee:0,phone:'PRIVATE',address:'PRIVATE',staff_note:'PRIVATE'})});
 const tracked=await track(trackingEvent);assert.equal(tracked.statusCode,200);assert.equal(JSON.parse(tracked.body).order.status,'preparing');assert.ok(!tracked.body.includes('PRIVATE'));assert.equal(tracked.headers['Cache-Control'],'no-store');
 global.fetch=async url=>({ok:true,json:async()=>String(url).endsWith('/rpc/customer_order_receipt')?{reference:'SS-RECEIPT',name:'Customer',phone:'08000000000',address:'Customer address',status:'preparing',payment_status:'paid'}:null});
 const receipt=await orderReceipt(trackingEvent);assert.equal(receipt.statusCode,200);assert.equal(JSON.parse(receipt.body).order.phone,'08000000000');
 const orderId=uuid(),paymentToken=uuid(),paymentPath=orderId+'/'+uuid()+'.webp';
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>({id:orderId,payment_status:'unpaid',bank_name:'Test Bank',account_name:'StackNSip',account_number:'0123456789'})};if(url.includes('/object/upload/sign/payment-receipts/'))return {ok:true,json:async()=>({token:'legacy-upload-token'})};throw Error('Unexpected legacy upload '+url);};
 const legacyUpload=await uploadPayment({...event,body:JSON.stringify({token:paymentToken,content_type:'image/webp'})});assert.equal(legacyUpload.statusCode,200);assert.equal(JSON.parse(legacyUpload.body).path.split('/')[0],orderId);
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>({id:orderId,payment_status:'unpaid'})};if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>webpBytes.buffer.slice(webpBytes.byteOffset,webpBytes.byteOffset+webpBytes.byteLength)};if(url.endsWith('/rpc/submit_payment_receipt')){assert.equal(JSON.parse(options.body).p_receipt_path,paymentPath);return {ok:true,json:async()=>({payment_status:'verification_pending'})};}throw Error('Unexpected legacy submission '+url);};
 assert.equal((await submitPayment({...event,body:JSON.stringify({token:paymentToken,path:paymentPath,payment_reference:'BANK-1'})})).statusCode,200);
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/staff_expired_quote_receipt_path')){assert.equal(JSON.parse(options.body).p_quote_id,quoteId);return {ok:true,json:async()=>quoteId+'/'+uuid()+'.webp'};}if(url.includes('/object/sign/payment-receipts/'))return {ok:true,json:async()=>({signedURL:'/object/sign/payment-receipts/private?token=short'})};throw Error('Unexpected signed receipt URL '+url);};
 const signedViewOk=await paymentReceipt({...event,headers:{...event.headers,authorization:'Bearer staff-token'},body:JSON.stringify({quote_id:quoteId})});assert.equal(signedViewOk.statusCode,200);assert.ok(JSON.parse(signedViewOk.body).url.startsWith('https://project.example.test/storage/v1/'));
 assert.equal(JSON.parse(signedViewOk.body).content_type,'image/webp');
 console.log('PASS: quote-first API, private receipt upload/validation, expired evidence response, private tracking, legacy receipt replacement, and staff signed receipt access.');
})().catch(error=>{console.error(error);process.exitCode=1;});
