const assert=require('node:assert/strict');
const submit=require('../netlify/functions/submit-order.cjs').handler;
const track=require('../netlify/functions/order-status.cjs').handler;
const orderReceipt=require('../netlify/functions/order-receipt.cjs').handler;
const invite=require('../netlify/functions/invite-staff.cjs').handler;
const uploadPayment=require('../netlify/functions/payment-upload-url.cjs').handler;
const submitPayment=require('../netlify/functions/payment-submit.cjs').handler;
const paymentReceipt=require('../netlify/functions/payment-receipt-url.cjs').handler;
const shared=require('../netlify/lib/shared.cjs');
const {randomUUID}=require('node:crypto');
const event={httpMethod:'POST',headers:{host:'example.netlify.app',origin:'https://example.netlify.app','x-nf-client-connection-ip':'192.0.2.1'},body:JSON.stringify({request_id:randomUUID(),customer:{name:'Test',phone:'08161248972',fulfillment:'Pickup',address:'',notes:''},items:[{id:'waffles:0',quantity:2,price:1}]})};
(async()=>{
 assert.equal((await submit({...event,httpMethod:'GET'})).statusCode,405);
 assert.equal((await submit({...event,headers:{...event.headers,origin:'https://elsewhere.test'}})).statusCode,403);
 assert.equal((await submit({...event,headers:{...event.headers,origin:'invalid'}})).statusCode,403);
 assert.equal((await submit({...event,body:'{'})).statusCode,400);
 const invalid=JSON.parse(event.body);invalid.customer.phone='BAD08161248972BAD';assert.equal((await submit({...event,body:JSON.stringify(invalid)})).statusCode,400);
 delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SECRET_KEY;
 assert.equal((await submit(event)).statusCode,503);
 process.env.SUPABASE_URL='https://project.example.test';process.env.SUPABASE_SECRET_KEY='sb_secret_TEST_NOT_A_REAL_KEY';
 let sent;global.fetch=async(url,options)=>{sent={url,options,payload:JSON.parse(options.body)};return {ok:true,json:async()=>({reference:'SS-SAVED',subtotal:15000,delivery_fee:0,items:[]})};};
 const saved=await submit(event);assert.equal(saved.statusCode,200);assert.equal(JSON.parse(saved.body).order.reference,'SS-SAVED');
 assert.deepEqual(sent.payload.p_items,[{id:'waffles:0',quantity:2}]);assert.equal(sent.payload.p_fingerprint.length,64);assert.ok(!saved.body.includes(process.env.SUPABASE_SECRET_KEY));
 assert.notEqual(shared.fingerprint(event),shared.fingerprint({...event,headers:{...event.headers,'x-nf-client-connection-ip':'192.0.2.2'}}));
 assert.equal((await invite(event)).statusCode,401);
 global.fetch=async()=>({ok:true,json:async()=>false});assert.equal((await invite({...event,headers:{...event.headers,authorization:'Bearer outsider'}})).statusCode,403);
 global.fetch=async()=>({ok:false,json:async()=>({message:'PRIVATE DATABASE ERROR '+process.env.SUPABASE_SECRET_KEY})});
 const failure=await submit(event);assert.equal(failure.statusCode,503);assert.ok(!failure.body.includes('PRIVATE'));assert.ok(!failure.body.includes(process.env.SUPABASE_SECRET_KEY));
 const trackingEvent={...event,body:JSON.stringify({token:JSON.parse(event.body).request_id})};
 assert.equal((await track({...trackingEvent,httpMethod:'GET'})).statusCode,405);
 assert.equal((await track({...trackingEvent,headers:{...event.headers,origin:'https://other.test'}})).statusCode,403);
 assert.equal((await track({...trackingEvent,body:JSON.stringify({token:'SS-GUESSED-REFERENCE'})})).statusCode,400);
 global.fetch=async()=>({ok:true,json:async()=>null});assert.equal((await track(trackingEvent)).statusCode,404);
 global.fetch=async()=>({ok:true,json:async()=>({reference:'SS-TRACKED',status:'preparing',items:[],subtotal:100,delivery_fee:0,total:100,phone:'PRIVATE',address:'PRIVATE',staff_note:'PRIVATE'})});
 const tracked=await track(trackingEvent);assert.equal(tracked.statusCode,200);assert.equal(JSON.parse(tracked.body).order.status,'preparing');assert.ok(!tracked.body.includes('PRIVATE'));assert.ok(!('phone' in JSON.parse(tracked.body).order));assert.ok(!('address' in JSON.parse(tracked.body).order));assert.equal(tracked.headers['Cache-Control'],'no-store');
 global.fetch=async(url)=>({ok:true,json:async()=>url.endsWith('/rpc/customer_order_receipt')?{reference:'SS-RECEIPT',name:'Customer',phone:'08000000000',address:'Customer address',status:'preparing',payment_status:'paid'}:null});const customerReceipt=await orderReceipt(trackingEvent);assert.equal(customerReceipt.statusCode,200);assert.equal(JSON.parse(customerReceipt.body).order.phone,'08000000000');
 const orderId='552f7a02-c548-4741-8f37-3ad8db2992d8',submissionId='453ecb0f-1bb9-4b58-bc08-cc46fbdac8a2',receiptPath=orderId+'/a8d72806-e9d7-4af6-bddb-75f72b7fdfe1.pdf';let paymentRpc=[];
 const paymentOrder={id:orderId,payment_status:'unpaid',bank_name:'Test Bank',account_name:'StackNSip',account_number:'0123456789'};
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>paymentOrder};if(url.includes('/object/upload/sign/payment-receipts/'))return {ok:true,json:async()=>({token:'signed-upload-token'})};throw Error('Unexpected payment URL '+url);};
 const uploadRequest={...trackingEvent,body:JSON.stringify({token:JSON.parse(event.body).request_id,content_type:'application/pdf'})};const upload=await uploadPayment(uploadRequest);assert.equal(upload.statusCode,200);const uploadBody=JSON.parse(upload.body);assert.equal(uploadBody.path.split('/')[0],orderId);assert.equal(uploadBody.token,'signed-upload-token');assert.ok(!upload.body.includes(process.env.SUPABASE_SECRET_KEY));
 const uploadBad=await uploadPayment({...uploadRequest,body:JSON.stringify({token:JSON.parse(event.body).request_id,content_type:'application/x-msdownload'})});assert.equal(uploadBad.statusCode,400);
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>paymentOrder};if(url.includes('/object/authenticated/payment-receipts/')){const bytes=Buffer.from('%PDF-1.7 test');return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};}if(url.endsWith('/rpc/submit_payment_receipt')){paymentRpc.push(JSON.parse(options.body));return {ok:true,json:async()=>({payment_status:'verification_pending'})};}throw Error('Unexpected submit URL '+url);};
 const submitted=await submitPayment({...trackingEvent,body:JSON.stringify({token:JSON.parse(event.body).request_id,path:uploadBody.path,payment_reference:'BANK-123'})});assert.equal(submitted.statusCode,200);assert.equal(paymentRpc[0].p_receipt_path,uploadBody.path);assert.equal(paymentRpc[0].p_payment_reference,'BANK-123');assert.ok(!submitted.body.includes(process.env.SUPABASE_SECRET_KEY));
 for(const [extension,bytes] of [['jpg',Buffer.from([0xff,0xd8,0xff,0xdb])],['png',Buffer.from([137,80,78,71,13,10,26,10,0])]]){global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>paymentOrder};if(url.includes('/object/authenticated/payment-receipts/'))return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};if(url.endsWith('/rpc/submit_payment_receipt'))return {ok:true,json:async()=>({payment_status:'verification_pending'})};throw Error('Unexpected image URL '+url);};const path=orderId+'/'+randomUUID()+'.'+extension,result=await submitPayment({...trackingEvent,body:JSON.stringify({token:JSON.parse(event.body).request_id,path,payment_reference:''})});assert.equal(result.statusCode,200);}
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/track_order'))return {ok:true,json:async()=>paymentOrder};if(url.includes('/object/authenticated/payment-receipts/')){const bytes=Buffer.from('not actually a PDF');return {ok:true,arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)};}if(options.method==='DELETE')return {ok:true,json:async()=>({})};throw Error('Unexpected invalid file URL '+url);};const invalidFile=await submitPayment({...trackingEvent,body:JSON.stringify({token:JSON.parse(event.body).request_id,path:orderId+'/'+randomUUID()+'.pdf',payment_reference:''})});assert.equal(invalidFile.statusCode,400);
 global.fetch=async(url,options)=>{url=String(url);if(url.endsWith('/rpc/customer_payment_receipt_path')||url.endsWith('/rpc/staff_payment_receipt_path'))return {ok:true,json:async()=>receiptPath};if(url.includes('/object/sign/payment-receipts/'))return {ok:true,json:async()=>({signedURL:'/object/sign/payment-receipts/'+receiptPath+'?token=temporary'})};throw Error('Unexpected receipt URL '+url);};
 const viewCustomer=await paymentReceipt({...trackingEvent,body:JSON.stringify({token:JSON.parse(event.body).request_id,submission_id:submissionId})});assert.equal(viewCustomer.statusCode,200);assert.equal(JSON.parse(viewCustomer.body).expires_in,120);assert.match(JSON.parse(viewCustomer.body).url,/temporary/);
 const viewStaff=await paymentReceipt({...trackingEvent,headers:{...event.headers,authorization:'Bearer staff-session-token'},body:JSON.stringify({submission_id:submissionId})});assert.equal(viewStaff.statusCode,200);
 console.log('PASS: method/origin checks; malformed requests; browser price ignored; private server keys; owner-only invitations; safe API errors.');
})().catch(e=>{console.error(e);process.exitCode=1;});
