const assert=require('node:assert/strict');
const submit=require('../netlify/functions/submit-order.cjs').handler;
const track=require('../netlify/functions/order-status.cjs').handler;
const invite=require('../netlify/functions/invite-staff.cjs').handler;
const shared=require('../netlify/lib/shared.cjs');
const {randomUUID}=require('node:crypto');
const event={httpMethod:'POST',headers:{host:'example.netlify.app',origin:'https://example.netlify.app','x-nf-client-connection-ip':'192.0.2.1'},body:JSON.stringify({request_id:randomUUID(),customer:{name:'Test',phone:'08161248972',fulfillment:'Pickup',address:'',notes:''},items:[{id:'waffles:0',quantity:2,price:1}]})};
(async()=>{
 assert.equal((await submit({...event,httpMethod:'GET'})).statusCode,405);
 assert.equal((await submit({...event,headers:{...event.headers,origin:'https://elsewhere.test'}})).statusCode,403);
 assert.equal((await submit({...event,headers:{...event.headers,origin:'invalid'}})).statusCode,403);
 assert.equal((await submit({...event,body:'{'})).statusCode,400);
 const invalid=JSON.parse(event.body);invalid.customer.phone='BAD08161248972BAD';assert.equal((await submit({...event,body:JSON.stringify(invalid)})).statusCode,400);
 delete process.env.SUPABASE_URL;delete process.env.SUPABASE_SECRET_KEY;
 assert.equal((await submit(event)).statusCode,503);
 process.env.SUPABASE_URL='https://project.example.test';process.env.SUPABASE_SECRET_KEY='sb_secret_TEST_NOT_A_REAL_KEY';
 let sent;global.fetch=async(url,options)=>{sent={url,options,payload:JSON.parse(options.body)};return {ok:true,json:async()=>({reference:'SS-SAVED',subtotal:15000,delivery_fee:0,items:[]})};};
 const saved=await submit(event);assert.equal(saved.statusCode,200);assert.equal(JSON.parse(saved.body).order.reference,'SS-SAVED');
 assert.deepEqual(sent.payload.p_items,[{id:'waffles:0',quantity:2}]);assert.equal(sent.payload.p_fingerprint.length,64);assert.ok(!saved.body.includes(process.env.SUPABASE_SECRET_KEY));
 assert.notEqual(shared.fingerprint(event),shared.fingerprint({...event,headers:{...event.headers,'x-nf-client-connection-ip':'192.0.2.2'}}));
 assert.equal((await invite(event)).statusCode,401);
 global.fetch=async()=>({ok:true,json:async()=>false});assert.equal((await invite({...event,headers:{...event.headers,authorization:'Bearer outsider'}})).statusCode,403);
 global.fetch=async()=>({ok:false,json:async()=>({message:'PRIVATE DATABASE ERROR '+process.env.SUPABASE_SECRET_KEY})});
 const failure=await submit(event);assert.equal(failure.statusCode,503);assert.ok(!failure.body.includes('PRIVATE'));assert.ok(!failure.body.includes(process.env.SUPABASE_SECRET_KEY));
 const trackingEvent={...event,body:JSON.stringify({token:JSON.parse(event.body).request_id})};
 assert.equal((await track({...trackingEvent,httpMethod:'GET'})).statusCode,405);
 assert.equal((await track({...trackingEvent,headers:{...event.headers,origin:'https://other.test'}})).statusCode,403);
 assert.equal((await track({...trackingEvent,body:JSON.stringify({token:'SS-GUESSED-REFERENCE'})})).statusCode,400);
 global.fetch=async()=>({ok:true,json:async()=>null});assert.equal((await track(trackingEvent)).statusCode,404);
 global.fetch=async()=>({ok:true,json:async()=>({reference:'SS-TRACKED',status:'preparing',items:[],subtotal:100,delivery_fee:0,total:100,phone:'PRIVATE',address:'PRIVATE',staff_note:'PRIVATE'})});
 const tracked=await track(trackingEvent);assert.equal(tracked.statusCode,200);assert.equal(JSON.parse(tracked.body).order.status,'preparing');assert.ok(!tracked.body.includes('PRIVATE'));assert.equal(tracked.headers['Cache-Control'],'no-store');
 console.log('PASS: method/origin checks; malformed requests; browser price ignored; private server keys; owner-only invitations; safe API errors.');
})().catch(e=>{console.error(e);process.exitCode=1;});
