import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;
grant insert on storage.objects to authenticated;`);
await db.exec(fs.readFileSync('supabase/schema.sql','utf8'));await db.exec(fs.readFileSync('supabase/seed.sql','utf8'));
const owner=randomUUID(),staff=randomUUID(),outside=randomUUID();
await db.query('insert into auth.users values ($1,$2,now()),($3,$4,now()),($5,$6,now())',[owner,'umar.umar@st.futminna.edu.ng',staff,'staff@example.test',outside,'outside@example.test']);
async function role(name,uid=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role '+name);}
async function reject(fn,pattern){await assert.rejects(fn,pattern);}
await role('anon');assert.equal((await db.query('select count(*)::int as n from public.products')).rows[0].n,84);await reject(()=>db.query('select * from public.orders'),/permission denied/);await reject(()=>db.query("update public.products set price=1 where id='wafflin:0'"),/permission denied/);
const customer={name:'Sample Customer',phone:'08000000000',fulfillment:'Delivery',address:'Wuse, Abuja Municipal',notes:''},items=[{id:'wafflin:0',quantity:2}],id=randomUUID(),fingerprint='a'.repeat(64);
const submit=()=>db.query('select public.submit_order($1,$2,$3,$4) as result',[id,JSON.stringify(customer),JSON.stringify(items),fingerprint]);
await reject(submit,/permission denied/);
await role('authenticated',outside);assert.equal((await db.query('select count(*)::int as n from public.orders')).rows[0].n,0);assert.equal((await db.query('select public.is_staff() as ok')).rows[0].ok,false);await reject(()=>db.query("select public.set_staff('outside@example.test',true)"),/Owner access required/);
await role('service_role');const first=(await submit()).rows[0].result;assert.equal(first.subtotal,15000);assert.equal(first.delivery_fee,6500);assert.equal(first.total,21500);assert.equal((await submit()).rows[0].result.reference,first.reference);
await role('authenticated',owner);await db.query("select public.set_staff('staff@example.test',true)");await db.query("update public.products set price=8000 where id='wafflin:0'");assert.equal((await db.query("select version from public.products where id='wafflin:0'")).rows[0].version,2);let saved=(await db.query('select * from public.orders')).rows[0];assert.equal(saved.subtotal,15000);
await role('authenticated',staff);assert.equal((await db.query('select public.is_staff() as ok')).rows[0].ok,true);await db.query("insert into storage.objects(bucket_id,name) values('menu-images','test.jpg')");
let update=(await db.query('select public.update_order($1,$2,$3,$4,$5,$6) as result',[saved.id,1,'confirmed',7000,'Confirm delivery','unpaid'])).rows[0].result;assert.equal(update.version,2);assert.equal(update.delivery_fee,7000);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,1,'ready',7000,'','unpaid']),/order changed/);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,null,'ready',7000,'','unpaid']),/Invalid order update/);
await db.query("update public.products set available=false where id='wafflin:0'");await role('service_role');await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify(customer),JSON.stringify(items),fingerprint]),/item is unavailable/);await role('authenticated',owner);await db.query("update public.products set available=true where id='wafflin:0'");
await role('service_role');let pickup=(await db.query('select public.submit_order($1,$2,$3,$4) as result',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'wafflin:0',quantity:1,price:1}]),fingerprint])).rows[0].result;assert.equal(pickup.subtotal,8000);assert.equal(pickup.delivery_fee,0);
await role('authenticated',owner);await db.query("select public.set_staff('staff@example.test',false)");await role('authenticated',staff);assert.equal((await db.query('select count(*)::int as n from public.orders')).rows[0].n,0);await reject(()=>db.query("insert into storage.objects(bucket_id,name) values('menu-images','bad.jpg')"),/row-level security/);
await role('authenticated',owner);await db.query('update public.shop_settings set accepting_orders=false where id=true');await role('service_role');await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify(customer),JSON.stringify(items),fingerprint]),/Online orders are paused/);
await role('authenticated',owner);assert.ok((await db.query('select count(*)::int as n from public.audit_log')).rows[0].n>=6);
await role('service_role');
const tracked=(await db.query('select public.track_order($1) as result',[id])).rows[0].result;
assert.equal(tracked.status,'confirmed');assert.equal(tracked.delivery_fee,7000);assert.equal(tracked.reference,first.reference);
for(const key of ['name','phone','address','notes','staff_note','request_payload','fingerprint','request_id'])assert.equal(key in tracked,false);
assert.equal((await db.query('select public.track_order($1) as result',[randomUUID()])).rows[0].result,null);
await role('anon');await reject(()=>db.query('select public.track_order($1)',[id]),/permission denied/);
await role('authenticated',outside);await reject(()=>db.query('select public.track_order($1)',[id]),/permission denied/);
await role('authenticated',owner);await db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,2,'cancelled',7000,'PRIVATE NOTE','unpaid']);
await role('service_role');assert.equal((await db.query('select public.track_order($1) as result',[id])).rows[0].result.status,'cancelled');
await db.exec('reset role');await db.exec(fs.readFileSync('supabase/migrations/001_customer_tracking.sql','utf8'));
console.log('PASS: customer tracking follows staff status; invalid tokens return no order; no customer contact details or internal notes; no public direct RPC access; upgrade migration is safe to rerun.');
await db.close();console.log('PASS: 84 seed products; public privacy; staff roles/revocation; photo upload permissions; authoritative pricing; old order snapshots; idempotency; sold-out rejection; pickup fee; optimistic conflict checks; order pause; audit history.');
