import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;
grant usage on schema public,auth,storage to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;
grant insert on storage.objects to authenticated;`);
await db.exec(fs.readFileSync('supabase/schema.sql','utf8'));await db.exec(fs.readFileSync('supabase/seed.sql','utf8'));
await db.exec('alter default privileges in schema public grant all on tables to service_role;alter default privileges in schema public grant all on sequences to service_role;grant all on all tables in schema public to service_role;grant all on all sequences in schema public to service_role;');
const owner=randomUUID(),staff=randomUUID(),outside=randomUUID();
await db.query('insert into auth.users values ($1,$2,now()),($3,$4,now()),($5,$6,now())',[owner,'umar.umar@st.futminna.edu.ng',staff,'staff@example.test',outside,'outside@example.test']);
async function role(name,uid=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);await db.exec('set role '+name);}
async function reject(fn,pattern){await assert.rejects(fn,pattern);}
await role('anon');assert.equal((await db.query('select count(*)::int as n from public.products')).rows[0].n,84);await reject(()=>db.query('select * from public.orders'),/permission denied/);await reject(()=>db.query("update public.products set price=1 where id='wafflin:0'"),/permission denied/);
const customer={name:'Sample Customer',phone:'08000000000',fulfillment:'Delivery',address:'Wuse, Abuja Municipal',notes:''},items=[{id:'wafflin:0',quantity:2}],id=randomUUID(),fingerprint='a'.repeat(64);
const submit=()=>db.query('select public.submit_order($1,$2,$3,$4) as result',[id,JSON.stringify(customer),JSON.stringify(items),fingerprint]);
await reject(submit,/permission denied/);
await role('authenticated',outside);assert.equal((await db.query('select count(*)::int as n from public.orders')).rows[0].n,0);assert.equal((await db.query('select public.is_staff() as ok')).rows[0].ok,false);await reject(()=>db.query("select public.set_staff('outside@example.test',true)"),/Owner access required/);
await role('service_role');const first=(await submit()).rows[0].result;assert.equal(first.subtotal,15000);assert.equal(first.delivery_fee,6500);assert.equal(first.total,21500);assert.equal((await submit()).rows[0].result.reference,first.reference);
await role('authenticated',owner);await db.query("select public.set_staff('staff@example.test',true)");await db.query("update public.products set price=8000 where id='wafflin:0'");assert.equal((await db.query("select version from public.products where id='wafflin:0'")).rows[0].version,2);let saved=(await db.query('select * from public.orders')).rows[0];assert.equal(saved.subtotal,15000);
await role('authenticated',staff);assert.equal((await db.query('select public.is_staff() as ok')).rows[0].ok,true);await db.query("insert into storage.objects(bucket_id,name) values('menu-images','test.jpg')");
let update=(await db.query('select public.update_order($1,$2,$3,$4,$5,$6) as result',[saved.id,1,'confirmed',7000,'Confirm delivery','unpaid'])).rows[0].result;assert.equal(update.version,2);assert.equal(update.delivery_fee,7000);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,1,'ready',7000,'','unpaid']),/order changed/);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,null,'ready',7000,'','unpaid']),/Invalid order update/);
await db.query("update public.products set available=false where id='wafflin:0'");await role('service_role');await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify(customer),JSON.stringify(items),fingerprint]),/item is unavailable/);await role('authenticated',owner);await db.query("update public.products set available=true where id='wafflin:0'");
await role('service_role');let pickup=(await db.query('select public.submit_order($1,$2,$3,$4) as result',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'wafflin:0',quantity:1,price:1}]),fingerprint])).rows[0].result;assert.equal(pickup.subtotal,8000);assert.equal(pickup.delivery_fee,0);
await role('authenticated',owner);await db.query("select public.set_staff('staff@example.test',false)");await role('authenticated',staff);assert.equal((await db.query('select count(*)::int as n from public.orders')).rows[0].n,0);await reject(()=>db.query("insert into storage.objects(bucket_id,name) values('menu-images','bad.jpg')"),/row-level security/);
await role('authenticated',owner);await db.query('update public.shop_settings set accepting_orders=false where id=true');await role('service_role');await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify(customer),JSON.stringify(items),fingerprint]),/Online orders are paused/);
await role('authenticated',owner);assert.ok((await db.query('select count(*)::int as n from public.audit_log')).rows[0].n>=6);
await role('service_role');
const tracked=(await db.query('select public.track_order($1) as result',[id])).rows[0].result;
assert.equal(tracked.status,'confirmed');assert.equal(tracked.delivery_fee,7000);assert.equal(tracked.reference,first.reference);
for(const key of ['name','phone','address','notes','staff_note','request_payload','fingerprint','request_id'])assert.equal(key in tracked,false);
assert.equal((await db.query('select public.track_order($1) as result',[randomUUID()])).rows[0].result,null);
await role('anon');await reject(()=>db.query('select public.track_order($1)',[id]),/permission denied/);
await role('authenticated',outside);await reject(()=>db.query('select public.track_order($1)',[id]),/permission denied/);
await role('authenticated',owner);await db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[saved.id,2,'cancelled',7000,'PRIVATE NOTE','unpaid']);
await role('service_role');assert.equal((await db.query('select public.track_order($1) as result',[id])).rows[0].result.status,'cancelled');
await db.exec('reset role');await db.exec(fs.readFileSync('supabase/migrations/001_customer_tracking.sql','utf8'));
console.log('PASS: customer tracking follows staff status; invalid tokens return no order; no customer contact details or internal notes; no public direct RPC access; upgrade migration is safe to rerun.');
await db.exec(fs.readFileSync('supabase/migrations/002_bank_transfer_payments.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/002_bank_transfer_payments.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/004_delivery_receipt_before_staff.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/004_delivery_receipt_before_staff.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/005_offer_customizations.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/005_offer_customizations.sql','utf8'));
await role('authenticated',owner);await db.query("update public.shop_settings set accepting_orders=true,bank_name='Test Bank',account_name='StackNSip',account_number='0123456789' where id=true");
await role('service_role');
const customized=(await db.query('select public.submit_order($1,$2,$3,$4) as result',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'bubble-drops:0',quantity:1,extras:['extras:0','extras:8']}]),'e'.repeat(64)])).rows[0].result;
assert.equal(customized.subtotal,10100);assert.deepEqual(customized.items[0].extras.map(extra=>extra.name),['Chocolate','Rainbow Sprinkles']);
await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'bubble-drops:0',quantity:1,extras:['extras:0','extras:1','extras:2']}]),'f'.repeat(64)]),/Invalid extras/);
await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'bubble-drops:0',quantity:1,extras:['extras:0','extras:0']}]),'h'.repeat(64)]),/Invalid extras/);
await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify({...customer,fulfillment:'Pickup'}),JSON.stringify([{id:'bubble-drops:0',quantity:1,extras:['wafflin:0']}]),'g'.repeat(64)]),/unavailable/);
const secondToken=randomUUID();await db.query('select public.submit_order($1,$2,$3,$4)',[secondToken,JSON.stringify(customer),JSON.stringify(items),'c'.repeat(64)]);
const paymentOrder=(await db.query('select id from public.orders where request_id=$1',[secondToken])).rows[0],paymentOrderId=paymentOrder.id;
await role('authenticated',owner);assert.equal((await db.query('select count(*)::int as n from public.orders where id=$1',[paymentOrderId])).rows[0].n,0);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[paymentOrderId,1,'preparing',6500,'','unpaid']),/waiting for a customer payment receipt/);
await role('service_role');const paymentPath=paymentOrderId+'/'+randomUUID()+'.jpg';let payment=(await db.query('select public.submit_payment_receipt($1,$2,$3) as result',[secondToken,'TRANSFER-A',paymentPath])).rows[0].result;assert.equal(payment.payment_status,'verification_pending');
await role('authenticated',owner);assert.equal((await db.query('select count(*)::int as n from public.orders where id=$1',[paymentOrderId])).rows[0].n,1);const releasedStatus=(await db.query('select public.update_order($1,$2,$3,$4,$5,$6) as result',[paymentOrderId,1,'preparing',6500,'','verification_pending'])).rows[0].result;assert.equal(releasedStatus.status,'preparing');assert.equal(releasedStatus.payment_status,'verification_pending');
await role('service_role');const customerBToken=randomUUID();await db.query('select public.submit_order($1,$2,$3,$4)',[customerBToken,JSON.stringify({...customer,name:'Customer B',phone:'08000000001'}),JSON.stringify(items),'d'.repeat(64)]);await reject(()=>db.query('select public.submit_payment_receipt($1,$2,$3)',[customerBToken,'TRANSFER-A',paymentPath]),/Invalid receipt path/);
await reject(()=>db.query('select public.customer_payment_receipt_path($1,$2)',[id,payment.id]),/Receipt not found/);
await role('authenticated',outside);assert.equal((await db.query('select count(*)::int as n from public.payment_submissions')).rows[0].n,0);await reject(()=>db.query('select public.review_payment($1,$2,$3)',[payment.id,'verify','']),/Staff access required/);await reject(()=>db.query('update public.orders set payment_status=\'paid\' where id=$1',[paymentOrderId]),/permission denied/);
await role('authenticated',owner);const statusOnly=(await db.query('select public.update_order($1,$2,$3,$4,$5,$6) as result',[paymentOrderId,2,'preparing',6500,'','verification_pending'])).rows[0].result;assert.equal(statusOnly.status,'preparing');assert.equal(statusOnly.payment_status,'verification_pending');
let reviewed=(await db.query('select public.review_payment($1,$2,$3) as result',[payment.id,'reject','Payment amount does not match'])).rows[0].result;assert.equal(reviewed.payment_status,'rejected');
await role('service_role');const rejected=(await db.query('select public.track_order($1) as result',[secondToken])).rows[0].result;assert.equal(rejected.payment_rejection_reason,'Payment amount does not match');
const replacementPath=paymentOrderId+'/'+randomUUID()+'.webp';payment=(await db.query('select public.submit_payment_receipt($1,$2,$3) as result',[secondToken,'TRANSFER-B',replacementPath])).rows[0].result;assert.equal(payment.payment_status,'verification_pending');
await role('authenticated',owner);reviewed=(await db.query('select public.review_payment($1,$2,$3) as result',[payment.id,'verify',''])).rows[0].result;assert.equal(reviewed.payment_status,'paid');
await role('service_role');const finalOrder=(await db.query('select public.track_order($1) as result',[secondToken])).rows[0].result;assert.equal(finalOrder.status,'preparing');assert.equal(finalOrder.payment_status,'paid');assert.ok(finalOrder.payment_verified_at);assert.equal((await db.query('select count(*)::int as n from public.payment_submissions where order_id=$1',[paymentOrderId])).rows[0].n,2);
assert.equal((await db.query('select public.customer_payment_receipt_path($1,$2) as path',[secondToken,payment.id])).rows[0].path,replacementPath);
await role('anon');await reject(()=>db.query('select * from public.payment_submissions'),/permission denied/);await reject(()=>db.query('select public.submit_payment_receipt($1,$2,$3)',[secondToken,'','bad']),/permission denied/);
console.log('PASS: private payment submission history; customer token scoping; staff-only review; protected payment fields; rejection/re-upload/verification; order and payment statuses remain separate; migration reruns safely.');
await db.exec('reset role');
await db.exec(fs.readFileSync('supabase/migrations/006_configurable_offer_options.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/006_configurable_offer_options.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/007_quote_first_checkout.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/007_quote_first_checkout.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/008_receipt_checkout_refinements.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/008_receipt_checkout_refinements.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/009_paystack_payments.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/009_paystack_payments.sql','utf8'));
const pancakeSyrupGroup=(await db.query("select id,included_selections,maximum_selections from public.product_option_groups where product_id='mini-pancakes:2' and name='Syrups'")).rows[0];
await db.query('update public.product_option_groups set required=true,minimum_selections=included_selections where id=$1',[pancakeSyrupGroup.id]);
await db.exec(fs.readFileSync('supabase/migrations/010_included_options_are_optional.sql','utf8'));
const repairedPancakeGroup=(await db.query('select required,minimum_selections,included_selections,maximum_selections,version from public.product_option_groups where id=$1',[pancakeSyrupGroup.id])).rows[0];
assert.equal(repairedPancakeGroup.required,false);assert.equal(repairedPancakeGroup.minimum_selections,0);
assert.equal(repairedPancakeGroup.included_selections,pancakeSyrupGroup.included_selections);
assert.equal(repairedPancakeGroup.maximum_selections,pancakeSyrupGroup.maximum_selections);
const repairedPancakeVersion=repairedPancakeGroup.version;
await db.exec(fs.readFileSync('supabase/migrations/010_included_options_are_optional.sql','utf8'));
assert.equal((await db.query('select version from public.product_option_groups where id=$1',[pancakeSyrupGroup.id])).rows[0].version,repairedPancakeVersion);
await role('authenticated',owner);
await reject(()=>db.query("select * from public.shop_settings where id=true"),/permission denied|column/i);
await reject(()=>db.query("update public.shop_settings set bank_name='Not allowed' where id=true"),/permission denied/);
await db.query("select public.save_payment_settings('Test Bank','StackNSip','0123456789','Transfer the exact quoted amount.',1)");
assert.equal((await db.query('select public.get_payment_settings() as result')).rows[0].result.payment_instructions,'Transfer the exact quoted amount.');
let paymentVersion=(await db.query('select public.get_payment_settings() as result')).rows[0].result.settings_version;
await reject(()=>db.query("select public.save_payment_settings('Stale','Stale','000','Stale',1)"),/Payment settings changed in another session/);
await db.query("select public.save_payment_settings('Test Bank','StackNSip','0123456789','',2)");
await role('service_role');
await reject(()=>db.query('select public.create_order_quote($1,$2,$3,$4)',[randomUUID(),JSON.stringify({name:'Sample Customer',phone:'08000000000',fulfillment:'Pickup',address:'',notes:''}),JSON.stringify([{id:'wafflin:0',quantity:1,options:[]}]),'6'.repeat(64)]),/payment instructions are not configured/i);
await role('authenticated',owner);
await db.query("select public.save_payment_settings('Test Bank','StackNSip','0123456789','Transfer the exact quoted amount.',3)");
paymentVersion=(await db.query('select public.get_payment_settings() as result')).rows[0].result.settings_version;
await role('authenticated',staff);
await reject(()=>db.query('select public.get_payment_settings()'),/Owner access required/);
await reject(()=>db.query("select public.save_payment_settings('Other','Other','000','',2)"),/Owner access required/);
await role('anon');assert.ok((await db.query("select count(*)::int as n from public.product_option_groups where product_id='bubble-drops:0'")).rows[0].n>0);await reject(()=>db.query("update public.product_option_groups set available=false"),/permission denied/);
await role('service_role');
const optionGroup=(await db.query("select id from public.product_option_groups where product_id='bubble-drops:0' and name='Syrups'")).rows[0].id;
const syrupChoices=(await db.query('select id,additional_price from public.product_option_choices where group_id=$1 order by sort_order limit 1',[optionGroup])).rows;
const toppingsGroup=(await db.query("select id from public.product_option_groups where product_id='bubble-drops:0' and name='Toppings'")).rows[0].id;
const toppingChoices=(await db.query('select id,additional_price from public.product_option_choices where group_id=$1 order by sort_order limit 1',[toppingsGroup])).rows;
const quoteId=randomUUID(),quoteCustomer={...customer,fulfillment:'Pickup',address:''};
const quoteItems=[{id:'bubble-drops:0',quantity:1,options:[{group_id:optionGroup,choice_ids:syrupChoices.map(choice=>choice.id)},{group_id:toppingsGroup,choice_ids:toppingChoices.map(choice=>choice.id)}]}];
const orderCountBefore=(await db.query('select count(*)::int as n from public.orders')).rows[0].n;
const quote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[quoteId,JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'b'.repeat(64)])).rows[0].result;
const expectedExtras=syrupChoices[0].additional_price+toppingChoices[0].additional_price;
assert.equal(quote.total,8500+expectedExtras);assert.equal(quote.items[0].base_price,8500);assert.equal(quote.items[0].option_total,expectedExtras);assert.deepEqual(quote.items[0].extras.map(extra=>extra.included),[false,false]);assert.deepEqual(quote.items[0].extras.map(extra=>extra.price),[syrupChoices[0].additional_price,toppingChoices[0].additional_price]);
assert.equal(quote.payment_instructions,'Transfer the exact quoted amount.');
await role('authenticated',owner);
await db.query('select public.save_payment_settings($1,$2,$3,$4,$5)',['Changed Bank','Changed Account','999','New instructions.',paymentVersion]);
await role('service_role');
const retriedQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[quoteId,JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'b'.repeat(64)])).rows[0].result;
assert.equal(retriedQuote.bank_name,'Test Bank');assert.equal(retriedQuote.payment_instructions,'Transfer the exact quoted amount.');
await role('authenticated',owner);
await db.query('select public.save_payment_settings($1,$2,$3,$4,$5)',[
 'Test Bank','StackNSip','0123456789','Transfer the exact quoted amount.',
 (await db.query('select public.get_payment_settings() as result')).rows[0].result.settings_version
]);
await role('service_role');
const cardQuoteId=randomUUID(),cardCustomer={...quoteCustomer,email:'customer@example.test',payment_method:'paystack'};
const cardQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[cardQuoteId,JSON.stringify(cardCustomer),JSON.stringify(quoteItems),'5'.repeat(64)])).rows[0].result;
assert.equal(cardQuote.payment_method,'paystack');assert.equal(cardQuote.bank_name,null);
const cardReference='SS-'+randomUUID();
const cardStart=(await db.query('select public.start_paystack_transaction($1,$2) as result',[cardQuoteId,cardReference])).rows[0].result;
assert.equal(cardStart.amount_kobo,cardQuote.total*100);assert.equal(cardStart.email,'customer@example.test');
const retriedCardStart=(await db.query('select public.start_paystack_transaction($1,$2) as result',[cardQuoteId,'SS-'+randomUUID()])).rows[0].result;
assert.equal(retriedCardStart.reference,cardReference);
const cardPaid=(await db.query("select public.complete_paystack_transaction($1,'success',$2,'NGN','123456') as result",[cardReference,cardQuote.total*100])).rows[0].result;
assert.equal(cardPaid.status,'paid');assert.ok(cardPaid.tracking_token);
const cardOrder=(await db.query('select * from public.orders where request_id=$1',[cardQuoteId])).rows[0];
assert.equal(cardOrder.payment_method,'paystack');assert.equal(cardOrder.payment_status,'paid');assert.equal(cardOrder.status,'pending');
assert.equal((await db.query("select public.complete_paystack_transaction($1,'success',$2,'NGN','123456') as result",[cardReference,cardQuote.total*100])).rows[0].result.reference,cardPaid.reference);
assert.equal((await db.query('select count(*)::int as n from public.orders where request_id=$1',[cardQuoteId])).rows[0].n,1);
const lateCardId=randomUUID();
const lateCardQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[lateCardId,JSON.stringify(cardCustomer),JSON.stringify(quoteItems),'4'.repeat(64)])).rows[0].result;
const lateCardReference='SS-'+randomUUID();
await db.query('select public.start_paystack_transaction($1,$2)',[lateCardId,lateCardReference]);
await db.query("update public.order_quotes set expires_at=now()-interval '1 minute' where id=$1",[lateCardId]);
const lateCardResult=(await db.query("select public.complete_paystack_transaction($1,'success',$2,'NGN','654321') as result",[lateCardReference,lateCardQuote.total*100])).rows[0].result;
assert.equal(lateCardResult.status,'paid_review');assert.equal((await db.query('select count(*)::int as n from public.orders where request_id=$1',[lateCardId])).rows[0].n,0);
await role('authenticated',owner);await db.query("select public.set_staff('staff@example.test',true)");
await role('authenticated',staff);
assert.equal((await db.query('select count(*)::int as n from public.list_paystack_reviews()')).rows[0].n,1);
await db.query("select public.resolve_paystack_review($1,$2)",[lateCardReference,'Contacted customer to arrange manual follow-up.']);
assert.equal((await db.query('select status from public.paystack_transactions where reference=$1',[lateCardReference])).rows[0].status,'resolved');
await role('service_role');
const noExtrasQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify([{id:'bubble-drops:0',quantity:1,options:[{group_id:optionGroup,choice_ids:[]},{group_id:toppingsGroup,choice_ids:[]}]}]),'c'.repeat(64)])).rows[0].result;
assert.equal(noExtrasQuote.total,8500);assert.equal(noExtrasQuote.items[0].option_total,0);
const pancakeGroups=(await db.query("select id from public.product_option_groups where product_id='mini-pancakes:2' and available")).rows;
const pancakePrice=(await db.query("select price from public.products where id='mini-pancakes:2'")).rows[0].price;
const includedPancakeQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify([{id:'mini-pancakes:2',quantity:1,options:pancakeGroups.map(group=>({group_id:group.id,choice_ids:[]}))}]),'d'.repeat(64)])).rows[0].result;
assert.equal(includedPancakeQuote.total,pancakePrice);assert.equal(includedPancakeQuote.items[0].option_total,0);
await db.query("update public.products set available=false where id='bubble-drops:0'");
await reject(()=>db.query('select public.create_order_quote($1,$2,$3,$4)',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'e'.repeat(64)]),/15pcs is sold out/);
await db.query("update public.products set available=true where id='bubble-drops:0'");
await db.query('update public.product_option_choices set available=false where id=$1',[syrupChoices[0].id]);
await reject(()=>db.query('select public.create_order_quote($1,$2,$3,$4)',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'f'.repeat(64)]),/Chocolate in Syrups for 15pcs is sold out/);
await db.query('update public.product_option_choices set available=true where id=$1',[syrupChoices[0].id]);
const sauceGroup=(await db.query("select id from public.product_option_groups where product_id='wafflin:0' and name='Sauces'")).rows[0].id;
const unpricedSauce=(await db.query('select id from public.product_option_choices where group_id=$1 order by sort_order limit 1',[sauceGroup])).rows[0].id;
await reject(()=>db.query('select public.create_order_quote($1,$2,$3,$4)',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify([{id:'wafflin:0',quantity:1,options:[{group_id:sauceGroup,choice_ids:[unpricedSauce]}]}]),'d'.repeat(64)]),/Mustard in Sauces has no add-on price configured/);
assert.equal((await db.query('select count(*)::int as n from public.orders')).rows[0].n,orderCountBefore+1);
await db.query("update public.products set price=9999 where id='bubble-drops:0'");
const receiptPath=quoteId+'/'+randomUUID()+'.pdf';await db.query('select public.issue_quote_upload($1,$2,$3)',[quoteId,receiptPath,'application/pdf']);
const quoteReplacementPath=quoteId+'/'+randomUUID()+'.webp',replacement=(await db.query('select public.issue_quote_upload($1,$2,$3) as result',[quoteId,quoteReplacementPath,'image/webp'])).rows[0].result;
assert.deepEqual(replacement.replaced_paths,[receiptPath]);
await reject(()=>db.query('select public.validate_quote_receipt_upload($1,$2)',[quoteId,receiptPath]),/replaced or was not issued/);
assert.equal((await db.query('select public.validate_quote_receipt_upload($1,$2) as result',[quoteId,quoteReplacementPath])).rows[0].result.file_type,'image/webp');
const placedQuote=(await db.query('select public.place_quoted_order($1,$2,$3) as result',[quoteId,quoteReplacementPath,'TRANSFER-QUOTE'])).rows[0].result;
assert.equal(placedQuote.subtotal,8500+expectedExtras);assert.equal(placedQuote.total,8500+expectedExtras);
const quotedOrder=(await db.query('select * from public.orders where request_id=$1',[quoteId])).rows[0];
assert.equal(quotedOrder.payment_status,'verification_pending');assert.equal(quotedOrder.status,'pending');assert.equal(quotedOrder.subtotal,8500+expectedExtras);
await role('authenticated',owner);await reject(()=>db.query('select public.update_order($1,$2,$3,$4,$5,$6)',[quotedOrder.id,1,'preparing',0,'','verification_pending']),/Payment must be verified/);
const paymentSubmission=(await db.query('select id from public.payment_submissions where order_id=$1',[quotedOrder.id])).rows[0].id;
const reviewedQuote=(await db.query('select public.review_payment($1,$2,$3) as result',[paymentSubmission,'verify',''])).rows[0].result;assert.equal(reviewedQuote.payment_status,'paid');
const preparedQuote=(await db.query('select public.update_order($1,$2,$3,$4,$5,$6) as result',[quotedOrder.id,1,'preparing',0,'','paid'])).rows[0].result;assert.equal(preparedQuote.status,'preparing');
await role('service_role');
const unavailableQuoteId=randomUUID(),unavailableQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[unavailableQuoteId,JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'a'.repeat(64)])).rows[0].result;
const unavailablePath=unavailableQuoteId+'/'+randomUUID()+'.png';await db.query('select public.issue_quote_upload($1,$2,$3)',[unavailableQuoteId,unavailablePath,'image/png']);
await db.query("update public.products set available=false where id='bubble-drops:0'");
const unavailableResult=(await db.query('select public.place_quoted_order($1,$2,$3) as result',[unavailableQuoteId,unavailablePath,'TRANSFER-LATE'])).rows[0].result;
assert.equal(unavailableResult.error_code,'item_unavailable');assert.match(unavailableResult.message,/15pcs became unavailable/);assert.match(unavailableResult.message,/receipt is retained privately/i);assert.equal((await db.query('select reason from public.quote_receipt_evidence where quote_id=$1',[unavailableQuoteId])).rows[0].reason,'item_unavailable');
await db.query("update public.products set available=true where id='bubble-drops:0'");
const unavailableChoiceQuoteId=randomUUID(),unavailableChoiceQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[unavailableChoiceQuoteId,JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'7'.repeat(64)])).rows[0].result;
const unavailableChoicePath=unavailableChoiceQuoteId+'/'+randomUUID()+'.png';await db.query('select public.issue_quote_upload($1,$2,$3)',[unavailableChoiceQuoteId,unavailableChoicePath,'image/png']);
await db.query('update public.product_option_choices set available=false where id=$1',[syrupChoices[0].id]);
const unavailableChoiceResult=(await db.query('select public.place_quoted_order($1,$2,$3) as result',[unavailableChoiceQuoteId,unavailableChoicePath,'TRANSFER-LATE-CHOICE'])).rows[0].result;
assert.equal(unavailableChoiceResult.error_code,'item_unavailable');assert.match(unavailableChoiceResult.message,/Chocolate in Syrups for 15pcs became unavailable/);
await db.query('update public.product_option_choices set available=true where id=$1',[syrupChoices[0].id]);
const expiredQuoteId=randomUUID(),expiredQuote=(await db.query('select public.create_order_quote($1,$2,$3,$4) as result',[expiredQuoteId,JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'9'.repeat(64)])).rows[0].result;
await db.query('update public.order_quotes set expires_at=now()-interval \'1 minute\' where id=$1',[expiredQuoteId]);
const firstExpiredPath=expiredQuoteId+'/'+randomUUID()+'.jpg';await db.query('select public.issue_quote_upload($1,$2,$3)',[expiredQuoteId,firstExpiredPath,'image/jpeg']);
const expiredPath=expiredQuoteId+'/'+randomUUID()+'.jpg',lateIntent=(await db.query('select public.issue_quote_upload($1,$2,$3) as result',[expiredQuoteId,expiredPath,'image/jpeg'])).rows[0].result;
assert.equal(lateIntent.quote_expired,true);
const expiredResult=(await db.query('select public.place_quoted_order($1,$2,$3) as result',[expiredQuoteId,expiredPath,'TRANSFER-EXPIRED'])).rows[0].result;
assert.equal(expiredResult.error_code,'quote_expired');assert.equal((await db.query('select reason from public.quote_receipt_evidence where quote_id=$1',[expiredQuoteId])).rows[0].reason,'quote_expired');
await role('authenticated',owner);const exceptionPath=(await db.query('select public.staff_expired_quote_receipt_path($1) as path',[expiredQuoteId])).rows[0].path;assert.equal(exceptionPath,expiredPath);
await db.query('select public.resolve_expired_quote_receipt($1,$2)',[expiredQuoteId,'Customer contacted; awaiting follow-up']);assert.equal((await db.query('select review_status from public.quote_receipt_evidence where quote_id=$1',[expiredQuoteId])).rows[0].review_status,'resolved');
await role('service_role');await reject(()=>db.query('select public.submit_order($1,$2,$3,$4)',[randomUUID(),JSON.stringify(customer),JSON.stringify(items),'8'.repeat(64)]),/permission denied/);
await db.exec('reset role');
await db.exec(fs.readFileSync('supabase/migrations/011_order_card_submission.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/011_order_card_submission.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/012_release_receipt_verified_deliveries.sql','utf8'));
await db.exec(fs.readFileSync('supabase/migrations/012_release_receipt_verified_deliveries.sql','utf8'));
await role('authenticated',owner);
const currentSettings=(await db.query('select public.get_payment_settings() as result')).rows[0].result;
await db.query('select public.save_payment_settings($1,$2,$3,$4,$5)',['','','','',currentSettings.settings_version]);
await role('anon');
await reject(()=>db.query('select public.submit_order_card($1,$2,$3,$4)',[randomUUID(),JSON.stringify(quoteCustomer),JSON.stringify(quoteItems),'f'.repeat(64)]),/permission denied/);
await role('authenticated',owner);
const restoredSettings=(await db.query('select public.get_payment_settings() as result')).rows[0].result;
await db.query('select public.save_payment_settings($1,$2,$3,$4,$5)',['Test Bank','StackNSip','0123456789','Transfer the exact quoted amount.',restoredSettings.settings_version]);
await role('service_role');
const deliveryQuoteId=randomUUID(),deliveryCustomer={...quoteCustomer,fulfillment:'Delivery',address:'Wuse, Abuja Municipal'};
await db.query('select public.create_order_quote($1,$2,$3,$4)',[deliveryQuoteId,JSON.stringify(deliveryCustomer),JSON.stringify(quoteItems),'e'.repeat(64)]);
const deliveryReceiptPath=deliveryQuoteId+'/'+randomUUID()+'.pdf';
await db.query('select public.issue_quote_upload($1,$2,$3)',[deliveryQuoteId,deliveryReceiptPath,'application/pdf']);
await db.query('select public.place_quoted_order($1,$2,$3)',[deliveryQuoteId,deliveryReceiptPath,'TRANSFER-DELIVERY']);
assert.equal((await db.query('select staff_visible from public.orders where request_id=$1',[deliveryQuoteId])).rows[0].staff_visible,true);
const cardRequestId=randomUUID(),cardFingerprint='f'.repeat(64),cardOrderCustomer={...quoteCustomer,fulfillment:'Delivery',address:'Wuse, Abuja Municipal'};
const cardResult=(await db.query('select public.submit_order_card($1,$2,$3,$4) as result',[cardRequestId,JSON.stringify(cardOrderCustomer),JSON.stringify(quoteItems),cardFingerprint])).rows[0].result;
assert.ok(cardResult.reference.startsWith('SS-'));assert.equal(cardResult.tracking_token,cardRequestId);assert.ok(cardResult.total>0);
assert.equal(cardResult.items[0].extras.length,2);assert.ok(cardResult.items[0].extras.some(extra=>extra.group==='Syrups'));assert.ok(cardResult.items[0].extras.some(extra=>extra.group==='Toppings'));
assert.equal((await db.query('select public.submit_order_card($1,$2,$3,$4) as result',[cardRequestId,JSON.stringify(cardOrderCustomer),JSON.stringify(quoteItems),cardFingerprint])).rows[0].result.reference,cardResult.reference);
let cardRow=(await db.query('select * from public.orders where request_id=$1',[cardRequestId])).rows[0];
assert.equal(cardRow.payment_status,'unpaid');assert.equal(cardRow.payment_method,'bank_transfer');assert.equal(cardRow.staff_visible,false);
const cardReceiptPath=cardRow.id+'/'+randomUUID()+'.pdf';
await db.query('select public.submit_payment_receipt($1,$2,$3)',[cardRequestId,'TRANSFER-CARD',cardReceiptPath]);
cardRow=(await db.query('select * from public.orders where request_id=$1',[cardRequestId])).rows[0];
assert.equal(cardRow.payment_status,'verification_pending');assert.equal(cardRow.staff_visible,true);
assert.ok((await db.query('select count(*)::int as n from public.audit_log')).rows[0].n>=10);
console.log('PASS: option availability and paid-price snapshots; package allowances need no selections; repeatable option/quote migrations; receipt-first and order-card submission; quote price locks; late/unavailable evidence review; payment-gated fulfilment.');
await db.close();console.log('PASS: 84 seed products; public privacy; staff roles/revocation; photo upload permissions; authoritative pricing; old order snapshots; idempotency; sold-out rejection; pickup fee; optimistic conflict checks; order pause; audit history.');
