import {JSDOM} from 'jsdom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const script=name=>fs.readFileSync('public/assets/'+name,'utf8');
const tick=()=>new Promise(resolve=>setTimeout(resolve,20));
function browser(html){return new JSDOM(html,{url:'https://example.netlify.app/cart.html',runScripts:'outside-only'}).window;}
// Make Order opens the customer-details dialog before payment selection.
let draftWindow=browser(fs.readFileSync('public/cart.html','utf8'));draftWindow.eval(script('receipt.js'));const draftForm=draftWindow.document.getElementById('order-form'),checkoutDialog=draftWindow.document.getElementById('order-checkout'),cartContent=draftWindow.document.getElementById('cart-content');assert.equal(checkoutDialog.open,false);cartContent.innerHTML='<a class="button secondary" href="#order-checkout">Prepare WhatsApp order</a>';await tick();const makeOrder=cartContent.querySelector('[data-open-order-form]');assert.equal(makeOrder.textContent,'Make order');makeOrder.click();assert.equal(checkoutDialog.open,true);assert.ok(draftForm.querySelector('.customer-fields'));assert.deepEqual(Array.from(draftForm.querySelectorAll('[name="payment_method"]'),input=>input.value),['bank_transfer','paystack']);draftWindow.close();
// Unconfigured sites keep the existing static menu; configured failures never fall back to stale prices.
let w=browser('<p data-delivery-info></p>');let calls=[];w.fetch=async url=>{calls.push(url);return {ok:true,json:async()=>({categories:[]})};};w.eval(script('backend.js'));await w.StackBackend.getMenu();assert.deepEqual(calls,['assets/menu.json']);w.close();
w=browser('<p data-delivery-info></p>');w.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};w.fetch=async()=>({ok:false});w.eval(script('backend.js'));await assert.rejects(w.StackBackend.getMenu(),/live menu/);w.close();
// Missing option tables must not blank the public catalog, and checkout remains explicitly blocked.
w=browser('<div id="category-tiles"></div>');w.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};let missingOptionTable;
w.fetch=async url=>{url=String(url);if(url.includes('/product_option_')){missingOptionTable=url.split('/').pop().split('?')[0];return {ok:false,status:404,json:async()=>({code:'PGRST205'})};}if(url.includes('/categories?'))return {ok:true,json:async()=>[{id:'waffles',title:'Waffles',items:[],photo:'',photo_alt:'',photo_generated:false}]};if(url.includes('/products?'))return {ok:true,json:async()=>[]};if(url.includes('/shop_settings?'))return {ok:true,json:async()=>[{id:true,delivery_fee:6500,delivery_area:'Abuja Municipal',delivery_note:'',accepting_orders:true}]};throw Error('Unexpected menu request '+url);};
w.console.error=()=>{};w.StackShop={refresh(){}};w.eval(script('backend.js'));w.eval(script('menu.js'));await tick();assert.ok(['product_option_groups','product_option_choices'].includes(missingOptionTable));assert.equal(w.document.querySelector('.category-tile').textContent.includes('Waffles'),true);assert.match(w.document.querySelector('.menu-setup-warning').textContent,/online ordering is unavailable/i);w.close();
const blocked=browser(fs.readFileSync('public/cart.html','utf8'));blocked.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};let quoteRequests=0;blocked.StackBackend={configured:true,getMenu:async()=>({optionsAvailable:false})};blocked.fetch=async()=>{quoteRequests++;throw Error('Quote API should not be called');};blocked.eval(script('receipt.js'));blocked.eval(script('quote-checkout.js'));const blockedForm=blocked.document.getElementById('order-form');blockedForm.elements.name.value='Test Customer';blockedForm.elements.phone.value='08161248972';blocked.StackReceipt.setItems([{id:'waffles:0',name:'Waffle',quantity:1,available:true,options:[]}]);blockedForm.dispatchEvent(new blocked.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(quoteRequests,0);assert.match(blocked.document.getElementById('order-status').textContent,/migrations are applied/i);blocked.close();
// A missing Netlify function gets an actionable deployment message, not a JSON parse error.
const missingFunction=browser(fs.readFileSync('public/cart.html','utf8'));missingFunction.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};missingFunction.StackBackend={configured:true,getMenu:async()=>({optionsAvailable:true})};missingFunction.fetch=async()=>({ok:false,status:405,text:async()=>''});missingFunction.eval(script('receipt.js'));missingFunction.eval(script('quote-checkout.js'));const missingFunctionForm=missingFunction.document.getElementById('order-form');missingFunctionForm.elements.name.value='Test Customer';missingFunctionForm.elements.phone.value='08161248972';missingFunction.StackReceipt.setItems([{id:'waffles:0',name:'Waffle',quantity:1,available:true,options:[]}]);missingFunctionForm.dispatchEvent(new missingFunction.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.match(missingFunction.document.getElementById('order-status').textContent,/create-order-quote.*HTTP 405.*VS Code Live Server cannot run Netlify Functions/i);assert.doesNotMatch(missingFunction.document.getElementById('order-status').textContent,/Unexpected end of JSON/i);missingFunction.close();
// Checkout creates a price-locked quote first, uploads a private receipt, then places the order.
w=browser(fs.readFileSync('public/cart.html','utf8'));w.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};w.StackBackend={configured:true};let placed=0,quotePayload,storageMethod;const uploadPaths=[];
const quote={quote_id:'b76b047a-54d4-42ef-9b34-fb3678b35a3e',expires_at:new Date(Date.now()+600000).toISOString(),items:[{name:'Test waffle',quantity:2,base_price:7500,option_total:500,price:8000,line_total:16000,extras:[{group:'Syrup',name:'Chocolate',price:500,included:false}]}],subtotal:16000,delivery_fee:7000,total:23000,bank_name:'Test Bank',account_name:'StackNSip',account_number:'0123456789',payment_instructions:'Transfer the exact quoted amount.'};
w.fetch=async(url,options={})=>{url=String(url);if(url.endsWith('/create-order-quote')){quotePayload=JSON.parse(options.body);return {ok:true,json:async()=>({quote})};}if(url.endsWith('/quote-upload-url')){const type=JSON.parse(options.body).content_type,extension=type==='image/webp'?'webp':'pdf',path=quote.quote_id+`/a8d72806-e9d7-4af6-bddb-75f72b7fdfe${uploadPaths.length}.${extension}`;uploadPaths.push(path);return {ok:true,json:async()=>({path,token:'signed-upload-token'})};}if(url.endsWith('/quote-validate-receipt'))return {ok:true,json:async()=>({validated:true,quote_expired:false})};if(url.includes('/storage/v1/object/upload/sign/')){storageMethod=options.method;return {ok:true};}if(url.endsWith('/place-quoted-order')){placed++;return {ok:true,json:async()=>({order:{reference:'SS-SAVED-REFERENCE',tracking_token:quote.quote_id,total:23000}})};}throw Error('Unexpected checkout URL '+url);};
w.eval(script('receipt.js'));w.eval(script('quote-checkout.js'));const f=w.document.getElementById('order-form');f.elements.name.value='Test Customer';f.elements.phone.value='08161248972';f.elements.fulfillment.value='Delivery';f.elements.address.value='Abuja';
w.StackReceipt.setItems([{id:'waffles:0',name:'Test waffle',category:'Waffles',base_price:7500,option_total:500,price:8000,quantity:2,available:true,options:[{group_id:'363453d1-2f17-466b-95d8-0b186827b01c',choice_ids:['66f7541c-88d8-4c33-83bf-51ca9ac83f9b']}]}]);
f.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(placed,0);assert.equal(quotePayload.items[0].options[0].choice_ids.length,1);assert.match(w.document.getElementById('order-result').textContent,/Test Bank/);
const receiptForm=w.document.getElementById('quote-receipt-form'),receiptInput=receiptForm.elements.receipt,pdfFile=new w.File(['%PDF-1.7 test'],'receipt.pdf',{type:'application/pdf'});assert.equal(receiptForm.querySelector('[data-place-order]').disabled,true);Object.defineProperty(receiptInput,'files',{value:[pdfFile],configurable:true});receiptInput.dispatchEvent(new w.Event('change',{bubbles:true}));receiptForm.querySelector('[data-upload-receipt]').click();await tick();await tick();assert.equal(placed,0);assert.equal(receiptForm.querySelector('[data-place-order]').disabled,false);
const webpFile=new w.File(['RIFF\x04\x00\x00\x00WEBP'],'receipt.webp',{type:'image/webp'});Object.defineProperty(receiptInput,'files',{value:[webpFile],configurable:true});receiptInput.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(receiptForm.querySelector('[data-place-order]').disabled,true);receiptForm.querySelector('[data-upload-receipt]').click();await tick();await tick();assert.equal(uploadPaths.length,2);assert.match(uploadPaths[1],/\.webp$/);assert.equal(storageMethod,'PUT');assert.equal(placed,0);assert.equal(receiptForm.querySelector('[data-place-order]').disabled,false);receiptForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(placed,1);assert.ok(w.document.querySelector('[data-track-order]').href.includes('track.html#token='));assert.match(w.document.getElementById('order-result').textContent,/SS-SAVED-REFERENCE/);assert.equal(w.localStorage.getItem('stacknsip-cart-v1'),null);w.close();
// Paystack opens the account-configured payment choices and confirms only through the server.
w=browser(fs.readFileSync('public/cart.html','utf8'));w.STACK_CONFIG={supabaseUrl:'https://project.example.test',supabasePublishableKey:'sb_publishable_TEST'};w.StackBackend={configured:true};
const cardQuote={quote_id:'5f06712a-64a2-49cb-ad14-c8922464db59',payment_method:'paystack',expires_at:new Date(Date.now()+600000).toISOString(),items:[{name:'Test waffle',quantity:1,base_price:8000,option_total:0,price:8000,line_total:8000,extras:[]}],subtotal:8000,delivery_fee:0,total:8000};
const cardReference='SS-8e53d23f-1f98-4f01-87d4-58d6fc6ad379';let popupOptions,popupOpened=false,verifiedReference,cardQuotePayload;
w.fetch=async(url,options={})=>{url=String(url);if(url.endsWith('/create-order-quote')){cardQuotePayload=JSON.parse(options.body);return {ok:true,json:async()=>({quote:cardQuote})};}if(url.endsWith('/initialize-paystack-payment'))return {ok:true,json:async()=>({reference:cardReference,email:'customer@example.test',amount_kobo:800000,public_key:'pk_test_public'})};if(url.endsWith('/verify-paystack-payment')){verifiedReference=JSON.parse(options.body).reference;return {ok:true,json:async()=>({payment:{status:'paid',reference:'SS-PAID-ORDER',tracking_token:cardQuote.quote_id,total:8000}})};}throw Error('Unexpected Paystack checkout URL '+url);};
w.PaystackPop={setup:options=>{popupOptions=options;return {openIframe:()=>{popupOpened=true;}};}};
w.eval(script('receipt.js'));w.eval(script('quote-checkout.js'));const cardForm=w.document.getElementById('order-form');cardForm.elements.name.value='Test Customer';cardForm.elements.phone.value='08161248972';cardForm.elements.email.value='customer@example.test';const paymentMethod=cardForm.querySelector('[name="payment_method"][value="paystack"]');paymentMethod.checked=true;paymentMethod.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(cardForm.elements.email.required,true);assert.equal(cardForm.querySelector('[data-checkout-submit]').textContent,'Continue to Paystack');
w.StackReceipt.setItems([{id:'waffles:0',name:'Test waffle',quantity:1,available:true,options:[]}]);cardForm.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.equal(cardQuotePayload.customer.payment_method,'paystack');assert.match(w.document.getElementById('order-result').textContent,/Paystack/);
w.document.querySelector('[data-paystack-checkout]').click();await tick();assert.equal(popupOpened,true);assert.equal(popupOptions.amount,800000);assert.equal(popupOptions.ref,cardReference);assert.equal('channels' in popupOptions,false);
popupOptions.callback({reference:cardReference});await tick();await tick();assert.equal(verifiedReference,cardReference);assert.match(w.document.getElementById('order-result').textContent,/Payment confirmed/);assert.ok(w.document.querySelector('[data-track-order]').href.includes('track.html#token='));w.close();
// The admin cannot pretend to authenticate before a project is connected.
w=browser(fs.readFileSync('public/admin.html','utf8'));w.eval(script('admin.js'));assert.equal(w.document.getElementById('setup-notice').hidden,false);assert.equal(w.document.getElementById('login-form').querySelector('button').disabled,true);w.close();
// Cart line totals and the cart subtotal update while a customer types a quantity.
w=browser(fs.readFileSync('public/cart.html','utf8'));w.localStorage.setItem('stacknsip-cart-v1',JSON.stringify({'toast:0':2}));let receiptItems=[];w.StackReceipt={setItems:rows=>{receiptItems=rows;}};w.StackBackend={getMenu:async()=>({categories:[{id:'toast',title:'Toast',items:[['Toast',250,'',{id:'toast:0'}]]}]})};w.eval(script('shop.js'));await tick();const paymentChoices=Array.from(w.document.querySelectorAll('.cart-payment-method input[name="payment_method"]'));assert.equal(w.document.querySelector('.cart-payment-method legend').textContent,'Choose payment method');assert.deepEqual(paymentChoices.map(input=>input.parentElement.textContent.trim()),['By Bank transfer','By Paystack']);paymentChoices[1].checked=true;paymentChoices[1].dispatchEvent(new w.Event('change',{bubbles:true}));let quantity=w.document.querySelector('.quantity-control input');assert.equal(w.document.querySelector('[data-cart-line-total]').textContent,'₦500');assert.equal(w.document.querySelector('[data-cart-subtotal]').textContent,'₦500');quantity.value='3';quantity.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(w.document.querySelector('[data-cart-line-total]').textContent,'₦750');assert.equal(w.document.querySelector('[data-cart-subtotal]').textContent,'₦750');assert.equal(w.document.querySelector('.cart-payment-method input[value="paystack"]').checked,true);assert.equal(JSON.parse(w.localStorage.getItem('stacknsip-cart-v1'))['toast:0'],3);assert.equal(receiptItems[0].quantity,3);w.close();
// Menu add-to-cart buttons update both persisted cart contents and visible counts.
w=browser('<div id="cart-content"></div><section id="order-checkout"></section><div id="product-detail"></div><span data-cart-count></span><span data-cart-item="toast:0"></span>');let addedItems=[];w.StackReceipt={setItems:rows=>{addedItems=rows;}};w.StackBackend={getMenu:async()=>({categories:[{id:'toast',title:'Toast',items:[['Toast',250,'',{id:'toast:0'}]]}]})};w.eval(script('shop.js'));await tick();const menuAdd=w.document.createElement('button');menuAdd.dataset.add='toast:0';w.document.body.append(menuAdd);menuAdd.click();assert.equal(JSON.parse(w.localStorage.getItem('stacknsip-cart-v1'))['toast:0'],1);assert.equal(w.document.querySelector('[data-cart-count]').textContent,'1');assert.equal(w.document.querySelector('[data-cart-item="toast:0"]').textContent,'1 in cart');assert.equal(addedItems[0].id,'toast:0');w.close();
// Product details show a live quantity total without adding it to the cart first.
w=new JSDOM('<div id="product-detail"></div>',{url:'https://example.netlify.app/product.html?item=toast%3A0',runScripts:'outside-only'}).window;w.StackBackend={getMenu:async()=>({categories:[{id:'toast',title:'Toast',items:[['Toast',250,'',{id:'toast:0'}]]}]})};w.eval(script('shop.js'));await tick();assert.equal(w.document.querySelector('[data-product-total]').textContent,'₦250');let productControl=w.document.querySelector('.detail-purchase .quantity-control'),productInput=productControl.querySelector('input');productControl.querySelector('[data-quantity="1"]').click();assert.equal(w.document.querySelector('[data-product-total]').textContent,'₦500');assert.equal(w.document.querySelector('[data-product-price-label]').textContent,'total for 2 items');productInput.value='3';productInput.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(w.document.querySelector('[data-product-total]').textContent,'₦750');assert.equal(w.document.querySelector('[data-product-price-label]').textContent,'total for 3 items');assert.deepEqual(JSON.parse(w.localStorage.getItem('stacknsip-cart-v1')) ,{});w.close();
console.log('PASS: live-menu failure handling; changed prices/availability; authoritative receipt reference and totals; stale-file removal; admin setup gate.');
